name: Gradle Plugin Test

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Integration Tests
        run: |
          ./gradlew publishToMavenLocal --console=plain
          ./gradlew test --console=plain
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        if: ${{ always() }}
        with:
          name: test-report
          path: |
            build/plugin/reports/**/*
